### ISSUE TITLE
Propagating state

### ISSUE THREAD

**Issue by IkemNwodo** [LukasLechnerDev/Kotlin-Coroutine-Use-Cases-on-Android#5]
Please how best can propagate state(like status) from the repository down to viewmodel using coroutine(no livedata usage in repository)?. 
I read a medium article about livedata usage in any other layers aside presentation being inappropriate

**Comment by LukasLechnerDev** [comment]
This sounds like a use case for using `Flow`. I will try to add some use cases that uses `Flow` in the future.
